include:
  - project: dwp/engineering/pipeline-solutions/gitlab/functions
    ref: 5.2.1
    file:
      - functions/node.gitlab-ci.yml
  # heroku publish
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/heroku-site-publish
    ref: 1-2-0
    file: ci-include-heroku-site-publish-base.yml
  - project: "dwp/engineering/pipeline-solutions/gitlab/fragments/node-audit"
    ref: 3.0.0
    file: "ci-include-node-audit-base.yml"
  - project: "dwp/engineering/pipeline-solutions/gitlab/fragments/node-outdated"
    ref: 2.5.1
    file: "ci-include-node-outdated-base.yml"



node-coverage:
  rules:
  - when: never

node-outdated:
  variables:
    IGNORE_DEV_DEPENDENCIES: false
  extends: .node-outdated-template
  allow_failure: true
  only:
    - /^[Ff]-.*$/

node-audit:
  extends: .node-audit-base
  allow_failure: true
  only:
    - /^[Ff]-.*$/

heroku-site-rc:
  stage: deploy
  extends: .heroku-site-publish-template
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_REF_NAME =~ /^f-.+$/
      variables:
        HEROKU_APP_NAME: attendance-allowance
      when: manual
      allow_failure: true
    - when: never

commitlint:
  script:
    - echo "Commitlint skipped"
  rules:
    - when: never
      
