include:
  - project:  'dwp/engineering/pipeline-solutions/gitlab/functions'
    ref: 4.16.0
    file:
      - functions/node.yml
  - project: 'dwp/engineering/pipeline-solutions/gitlab/fragments/heroku-site-publish'
    ref: 1-2-0
    file: 'ci-include-heroku-site-publish-base.yml'

variables:
  CREATE_TARBALL: "false"

# Disabed for prototype project
.node-coverage-rules:
  rules:
    when: never

# Disabed for prototype project
.node-sonarqube-rules:
  rules:
      when: never

# Disabed for prototype project
.code_quality-rules:
  rules:
      when: never

# Disabed for prototype project
.node-codelint-rules:
  rules:
      when: never

heroku-site-publish:
  extends: .heroku-site-publish-template
  stage: deploy
  variables:
    HEROKU_APP_NAME: attendance-allowance
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
