include:
  - project: dwp/engineering/pipeline-solutions/gitlab/functions
    ref: 5.2.1
    file:
      - functions/node.gitlab-ci.yml
  # heroku publish
  - project: dwp/engineering/pipeline-solutions/gitlab/fragments/heroku-site-publish
    ref: 1-2-0
    file: ci-include-heroku-site-publish-base.yml
  - project: "dwp/engineering/pipeline-solutions/gitlab/fragments/node-audit"
    ref: 3.0.0
    file: "ci-include-node-audit-base.yml"
  - project: "dwp/engineering/pipeline-solutions/gitlab/fragments/node-outdated"
    ref: 2.5.1
    file: "ci-include-node-outdated-base.yml"

variables:
  NODE_IMAGE: node:22.14.0-alpine@sha256:9bef0ef1e268f60627da9ba7d7605e8831d5b56ad07487d24d1aa386336d1944
  NODE_VERSION: "22.12.0-alpine3.20"
  FUNCTIONS_SONARQUBE_ENABLED: "false"

node-coverage:
  rules:
  - when: never

node-outdated:
  variables:
    IGNORE_DEV_DEPENDENCIES: false
  extends: .node-outdated-template
  allow_failure: true
  only:
    - /^[Ff]-.*$/

node-audit:
  extends: .node-audit-base
  allow_failure: true
  only:
    - /^[Ff]-.*$/

heroku-site-rc:
  stage: deploy
  extends: .heroku-site-publish-template
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_REF_NAME =~ /^f-.+$/
      variables:
        HEROKU_APP_NAME: pip-apply-review
      when: manual
      allow_failure: true
    - when: never

commitlint:
  script:
    - echo "Commitlint skipped"
  rules:
    - when: never
      
